name: Build image and push to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'config.hcl'
      - '.github/workflows/*.yaml'

env:
  DOCKER_REGISTRY: teokyllc.azurecr.io
  DOCKER_REGISTRY_USERNAME: teokyllc

jobs:

  build-versioned-tag:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}-${{ matrix.vault-version }}
    strategy:
      matrix:
        include:
          - name: vault
            vault-version: 1.9.4
            dockerfile: Dockerfile

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get certs
        run: |
          echo "::add-mask::certs"
          echo "${{ secrets.CA_CERT }}" > vault.ca.crt
          echo "${{ secrets.VAULT_CERT }}" > vault.crt
          echo "${{ secrets.VAULT_KEY }}" > vault.key

      - name: Replace token in config.hcl
        run: sed -i 's/#TOKEN#/${{ secrets.SA_ACCESS_KEY }}/g' config.hcl

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ matrix.name }}:${{ matrix.vault-version }}


  build-latest-tag:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}-latest
    strategy:
      matrix:
        include:
          - name: vault
            dockerfile: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get certs
        run: |
          echo "::add-mask::certs"
          echo "${{ secrets.CA_CERT }}" > vault.ca.crt
          echo "${{ secrets.VAULT_CERT }}" > vault.crt
          echo "${{ secrets.VAULT_KEY }}" > vault.key

      - name: Replace token in config.hcl
        run: sed -i 's/#TOKEN#/${{ secrets.SA_ACCESS_KEY }}/g' config.hcl

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and Push Latest Tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ matrix.name }}:latest