name: Build image and push to DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'config.hcl'

env:
  DOCKER_REGISTRY_USERNAME: johndvs

jobs:
  prereqs:
    runs-on: ubuntu-latest
    name: Prerequisites

    steps:
      - name: Get certs
        run: |
          echo "::add-mask::certs"
          echo "${{ secrets.CA_CERT }}" > ca.crt
          echo "${{ secrets.VAULT_CERT }}" > vault.crt
          echo "${{ secrets.VAULT_KEY }}" > vault.key

      - name: Cache certs
        uses: actions/cache@v2
        with:
          key: certs
          path: |
            ca.crt
            vault.crt
            vault.key

  build-versioned-tag:
    needs: prereqs
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}-${{ matrix.vault-version }}
    strategy:
      matrix:
        include:
          - name: vault
            vault-version: 1.9.4
            dockerfile: Dockerfile

    steps:

      - name: test
        run: |
          ls -lah certs

      - name: Set outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and Push Versioned Tags
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.name }}:${{ matrix.vault-version }}
            ${{ matrix.name }}:${{ matrix.vault-version }}-${{ steps.vars.outputs.sha_short }}


  build-latest-tag:
    needs: prereqs
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}-latest
    strategy:
      matrix:
        include:
          - name: vault
            dockerfile: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and Push Latest Tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY_USERNAME }}/${{ matrix.name }}:latest